export const TRANSLATIONS_SERVICE = 'TRANSLATIONS_SERVICE';
export const MANAGE_TRANSLATIONS = 'MANAGE_TRANSLATIONS';
export const AUTO_TRANSLATE = 'AUTO_TRANSLATE';
export const AI_SETTINGS_REPOSITORY = 'AI_SETTINGS_REPOSITORY';
